package com.example.regularincomeandinstallmentsampling

const val TEXT_NONE = "NONE"
const val TEXT_EVERY_DAY = "EVERY DAY"
const val TEXT_EVERY_WEEK = "EVERY WEEK"
const val TEXT_EVERY_TWO_WEEKS = "EVERY TWO WEEKS"
const val TEXT_EVERY_FOUR_WEEKS = "EVERY FOUR WEEKS"
const val TEXT_EVERY_MONTH = "EVERY MONTH"
const val TEXT_THE_END_OF_THE_MONTH = "THE END OF THE MONTH"
const val TEXT_EVERY_TWO_MONTHS = "EVERY TWO MONTHS"
const val TEXT_EVERY_THREE_MONTHS = "EVERY THREE MONTHS"
const val TEXT_EVERY_FOUR_MONTHS = "EVERY FOUR MONTHS"
const val TEXT_EVERY_SIX_MONTHS = "EVERY SIX MONTHS"
const val TEXT_EVERY_YEAR = "EVERY YEAR"

const val TEXT_PERIOD = "Period"
const val TEXT_SHOW_PERIOD = "Show Period"

val REPEAT_ITEM_LIST = arrayOf(
    TEXT_EVERY_DAY,
    TEXT_EVERY_WEEK,
    TEXT_EVERY_TWO_WEEKS,
    TEXT_EVERY_FOUR_WEEKS,
    TEXT_EVERY_MONTH,
    TEXT_THE_END_OF_THE_MONTH,
    TEXT_EVERY_TWO_MONTHS,
    TEXT_EVERY_THREE_MONTHS,
    TEXT_EVERY_FOUR_MONTHS,
    TEXT_EVERY_SIX_MONTHS,
    TEXT_EVERY_YEAR
)

const val TEXT_REPEAT = "repeat"
const val TEXT_NAME = "name"
const val TEXT_AMOUNT = "amount"
const val TEXT_DATE = "date"